### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by OlegSmelov** [soutaro/vscode-rbs-syntax#8]
Hello 👋 , what is the license for these files?

I've been working on a Sublime Text port (https://github.com/OlegSmelov/sublime-rbs-syntax), so I'm wondering if it's okay to make derivative works.

**Comment by soutaro** [comment]
Added MIT LICENSE (https://github.com/soutaro/vscode-rbs-syntax/commit/164e36d3d39c0f187a04f7370cea7ba22453b662). Sorry for the huge delay...
